name: pull

on:
  workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull from another repository
        uses: ipfs-examples/actions-pull-directory-from-repo@main
        with:
          source-repo: "ipfs-examples/helia-examples"
          source-folder-path: "examples/helia-101"
          source-branch: "main"
          target-branch: "main"
          git-username: github-actions
          git-email: github-actions@github.com
